server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root

  cloud:
    zookeeper:
      connect-string: 172.17.198.149:2181




